### ISSUE TITLE
Denied Access

### ISSUE THREAD

**Issue by aeishan** [BearHeart3/B07Lab5#3]
When trying to push my branch, I was told I didn't have access to the repo. I don't really get why since I'm pretty sure I was added as a contributor, but in any case, can I get access to the repository?

**Comment by BearHeart3** [comment]
I double checked the contributor list and permissions and you should be able to push to the repo. Maybe it could be something on your end. 
This forum says that you may need to integrate the remote changes via **git pull origin master** in order to be able to push:
https://stackoverflow.com/questions/47009136/how-can-collaborators-push-their-changes-to-my-repo-in-github
